version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.18
        auth:
          username: $DOCKER_USER_NAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: echo "Hello, World"
