version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.18
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t sample-api:latest -f app/docker/Dockerfile .
