version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.18.4
        auth:
          username: $DOCKER_USER_NAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: docker build -t api-sample:latest -f app/docker/Dockerfile .
