version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.18.0-alpine
    steps:
      - checkout
      - run:
          name: Test
          command: cd app && go test v
      - run:
          name: Build
          command: go build
