version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.18.4
        auth:
          username: $DOCKER_USER_NAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: Download test dependencies
          command: go get github.com/stretchr/testify/assert
      - run:
          name: Test
          command: go test -v ./app
      - run:
          name: Build Docker Image
          command: docker build -t $AWS_ECR_REPOSITORY_NAME/sample-api:latest -f app/docker/Dockerfile .


