version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.18.4
        auth:
          username: $DOCKER_USER_NAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: go get github.com/stretchr/testify/assert
      - run: cd app && go test -v
